# Generated by Django 2.2.1 on 2019-05-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='paidAmount',
        ),
        migrations.AddField(
            model_name='payment',
            name='customerName',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='itemName',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
